[package]
name = "geomag-jni"
version = "0.0.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
geomag = { git = "https://github.com/SanmerDev/libgeomag.git", tag = "v0.1.4" }
jni = "0.21.1"

[lib]
name = "jni"
crate_type = ["cdylib"]
