version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10
    labels: [ "github_actions" ]
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    labels: [ "dependencies" ]
    target-branch: main
    registries:
      - maven-google
      - gradle-plugin

registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  gradle-plugin:
    type: maven-repository
    url: "https://plugins.gradle.org/m2/"
